# safelist
branches:
  only:
  - master
  - next
  - next+

language: ocaml
sudo: required

before_install:
- sudo apt-get update -qq
- sudo apt-get install -y git -qq ocaml ocaml-native-compilers libgmp-dev libgtksourceview2.0-dev zlib1g-dev libgtk2.0-dev libexpat1-dev
- git status

install:
- sudo wget -O /usr/local/bin/opam https://github.com/ocaml/opam/releases/download/2.0.1/opam-2.0.1-x86_64-linux
- sudo chmod a+x /usr/local/bin/opam
- export OPAMYES=1
- opam init --disable-sandboxing --bare

script:
- sh ./travis.sh
