name: Build documentation
on: push

jobs:
  build_doc:
    name: Build documentation

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Retrieve opam cache
        uses: actions/cache@v2
        id: cache-opam
        with:
          path: ~/.opam
          key: v1-${{ runner.os }}-alt-ergo-4.10.0-${{ hashFiles('*.opam') }}

      - name: Use OCaml 4.10.0
        uses: avsm/setup-ocaml@v1
        with:
          ocaml-version: 4.10.0

      - name: Install sphinx dependencies
        run: |
          sudo apt install -yqq python3-sphinx python3-sphinx-rtd-theme
          opam install -y dune odoc

      - name: Install ocaml documentation dependencies
        run: opam install odoc

      - run: opam pin add . -y --no-action
      - run: opam depext -y alt-ergo alt-ergo-lib alt-ergo-parsers altgr-ergo
        # if: steps.cache-opam.outputs.cache-hit != 'true'
      - run: opam install -y ./*.opam --deps-only --with-test
        # if: steps.cache-opam.outputs.cache-hit != 'true'
      - run: opam upgrade --fixup
        # if: steps.cache-opam.outputs.cache-hit == 'true'

      - name: Build documentation
        run: |
          eval $(opam env)
          rsc/extra/travis_doc_test.sh
