name: Documentation

on: push

jobs:
  docs:
    name: Sphinx documentation
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "docs/sphinx_docs/"
        build-command: "sphinx-build -b html . _build"
