name: Documentation

on:
  # Trigger the documentation build for any push, pull request and any branch
  # This build is also trigger when a commit is merged in next so we need to deploy the new gh-pages
  push:
  pull_request:
  branch:
    - next

jobs:
  ocaml_docs:
    # Build the documentation from the ocaml comments
    # If this test fails, no more test
    name: OCaml documentation

    strategy:
       matrix:
        os:
          - ubuntu-latest
        ocaml-version:
          - 4.10.0

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Retrieve opam cache
        uses: actions/cache@v2
        id: cache-opam
        with:
          path: ~/.opam
          key: v1-${{ runner.os }}-alt-ergo-${{ matrix.ocaml-version }}-${{ hashFiles('*.opam') }}
#          restore-keys: |
#            v1-${{ runner.os }}-opam-${{ matrix.ocaml-version }}-

      - name: Use OCaml ${{ matrix.ocaml-version }}
        uses: avsm/setup-ocaml@v1
        with:
          ocaml-version: ${{ matrix.ocaml-version }}

      - name: Set git user
        run: |
          git config --global user.name github-actions
          git config --global user.email github-actions-bot@users.noreply.github.com

      - run: opam pin add . -y --no-action
      - run: opam depext -y alt-ergo-lib alt-ergo-parsers alt-ergo altgr-ergo
        # if: steps.cache-opam.outputs.cache-hit != 'true'
      - run: opam install -y ./*.opam --deps-only --with-test
        # if: steps.cache-opam.outputs.cache-hit != 'true'
      - run: opam upgrade --fixup
        # if: steps.cache-opam.outputs.cache-hit == 'true'
      - run: opam install odoc
      - name: Make OCaml documentation
        run: opam exec -- make odoc

      - name: Upload ocaml documentation
        uses: actions/upload-artifact@v2
        with:
          name: ocaml_doc
          path: _build/default/_doc/_html/

  sphinx_docs:
    # Build the sphinx documentation
    name: Sphinx documentation

    needs: ocaml_docs

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: ammaraskar/sphinx-action@master
        with:
          docs-folder: "docs/sphinx_docs/"
          build-command: "sphinx-build -b html . _build"

      - run: ls docs/sphinx_docs
      - run: ls docs/sphinx_docs/_build

      - name: Upload sphinx documentation
        uses: actions/upload-artifact@v2
        with:
          name: sphinx_doc
          path: docs/sphinx_docs/_build

  deploy_docs:
    # Deploy the documentation
    name: Deploy documentation

    needs: sphinx_docs

    runs-on: ubuntu-latest

    steps:
      - name: Download ocaml documentation
        uses: actions/download-artifact@v2
        with:
          name: ocaml_doc
          path: docs/odoc/dev

      - name: Download sphinx documentation
        uses: actions/download-artifact@v2
        with:
          name: sphinx_doc
          path: docs

      - run: |
          touch docs/.nojekyll
          touch docs/odoc/.nojekyll
          touch docs/odoc/dev/.nojekyll

      - name: deploy-doc
        uses: JamesIves/github-pages-deploy-action@3.6.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: docs
          CLEAN: true
