name: Format

on: push

jobs:
  check_indentation:
    name: Check indentation

    strategy:
      matrix:
        os:
          - ubuntu-latest
        ocaml-version:
          - 4.10.0
        ocp-indent-version:
          - 1.8.1

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Retrieve opam cache
        uses: actions/cache@v2
        id: cache-opam
        with:
          path: ~/.opam
          key: v1-${{ runner.os }}-alt-ergo-${{ matrix.ocaml-version }}-${{ hashFiles('*.opam') }}
          # restore-keys: |
          #   v1-${{ runner.os }}-opam-${{ matrix.ocaml-version }}-

      - name: Use OCaml ${{ matrix.ocaml-version }}
        uses: avsm/setup-ocaml@v1
        with:
          ocaml-version: ${{ matrix.ocaml-version }}

      - name: Install ocp-indent ${{ matrix.ocp-indent-version }}
        run: opam install ocp-indent.${{ matrix.ocp-indent-version }}

      - name: Run check_indentation.sh script
        run: |
          eval $(opam env)
          rsc/extra/check_indentation.sh

  check_style:
    name: Check style

    strategy:
      matrix:
        os:
          - ubuntu-latest
        ocaml-version:
          - 4.10.0
        ocp-indent-version:
          - 1.8.1

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Retrieve opam cache
        uses: actions/cache@v2
        id: cache-opam
        with:
          path: ~/.opam
          key: v1-${{ runner.os }}-alt-ergo-${{ matrix.ocaml-version }}-${{ hashFiles('*.opam') }}
          # restore-keys: |
          #   v1-${{ runner.os }}-opam-${{ matrix.ocaml-version }}-

      - name: Use OCaml ${{ matrix.ocaml-version }}
        uses: avsm/setup-ocaml@v1
        with:
          ocaml-version: ${{ matrix.ocaml-version }}

      - name: Opam install check_style deps
        run: opam install stdlib-shims

      - name: Run check_style.sh script
        run: |
          eval $(opam env)
          rsc/extra/check_style.sh
