name: Format

on: push

env:
  OCAML_DEFAULT_VERSION: 4.10.0

jobs:
  check_indentation:
    # Check that all `.ml` and `.mli` file are correctly indent with ocp-indent
    name: Check indentation

    strategy:
      matrix:
        ocp-indent-version:
          - 1.8.1
        cache-name:
          - indentation

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Retrieve opam cache
        uses: actions/cache@v2
        id: cache-opam
        with:
          path: ~/.opam
          key: v1-${{ runner.os }}-alt-ergo-${{ matrix.cache-name }}-${{ env.OCAML_DEFAULT_VERSION }}-${{ hashFiles('*.opam') }}

      - name: Use OCaml ${{ env.OCAML_DEFAULT_VERSION }}
        uses: avsm/setup-ocaml@v1
        with:
          ocaml-version: ${{ env.OCAML_DEFAULT_VERSION }}

      - name: Install ocp-indent ${{ matrix.ocp-indent-version }}
        run: opam install ocp-indent.${{ matrix.ocp-indent-version }}

      - name: Run check_indentation.sh script
        run: opam exec -- rsc/extra/check_indentation.sh

  check_style:
    # Check that all `.ml` and `.mli` files don't have line longer than 80 characters
    name: Check style

    strategy:
      matrix:
        ocp-indent-version:
          - 1.8.1
        cache-name:
          - style

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Retrieve opam cache
        uses: actions/cache@v2
        id: cache-opam
        with:
          path: ~/.opam
          key: v1-${{ runner.os }}-alt-ergo-${{ matrix.cache-name }}-${{ env.OCAML_DEFAULT_VERSION }}-${{ hashFiles('*.opam') }}

      - name: Use OCaml ${{ env.OCAML_DEFAULT_VERSION }}
        uses: avsm/setup-ocaml@v1
        with:
          ocaml-version: ${{ env.OCAML_DEFAULT_VERSION }}

      - name: Opam install check_style deps
        run: opam install stdlib-shims

      - name: Run check_style.sh script
        run: opam exec -- rsc/extra/check_style.sh
